export const routes = {
  splash: 'Splash',
  home: 'Home',
  auth: 'Auth',
  phoneAuth: 'PhoneAuth',
  signupDetails: 'SignupDetails',
  onboarding: 'Onboarding',
  terms: 'TermsAndConditions',
  room: 'Room',
  profile: 'Profile',
  banned: 'Banned',
  settings: 'Settings',
  editProfile: 'EditProfile',
  bannerDetail: 'BannerDetail',
  createAgency: 'CreateAgency',
  changeAvatar: 'ChangeAvatar',
  demoRoom: 'DemoRoom',
  userProfile: 'UserProfile',
  comingSoon: 'ComingSoon',
  inAppBrowser: 'InAppBrowser',
  conversation: 'Conversation',
  userSearch: 'UserSearch',
  friendRequests: 'FriendRequests'
};
